### ISSUE TITLE
signalmaster doesn't work after upgrade to socket.io 1.2.1

### ISSUE THREAD

**Issue by lavende** [andyet/SimpleWebRTC#199]
I developed an application using SimpleWebRTC

i upgraded all old socket.io version in all node_modules I have installed.

I changed all the `socket.sessionid` to `io.engine.id` in simplewebrtc.js
and built it with socket.io-1.2.1.js

the same in the signalmaster, I changed the `io.sockets.clients(name)` to `io.sockets.adapter.rooms[name]` to get the specific room

to get copy the room data, i changed the `describeRoom` function to
```js
function describeRoom(name) {
        var clients = io.sockets.adapter.rooms[name];
        var result = {
            clients: {}
        };
        for (var client in clients) {
            result.clients[client.id] = clients[client];
        }
        return result;
    }
```

but it still doesn't work. it works well in socket.io version 0.9.16.

I logged that, it showed that two people are really in the same room, but the messages didn't delivery to each other. 

could anyone help me to figure out where I was wrong. Thx so much.
BTW, when will signalmaster upgrade to support the new version of socket.io ?

**Comment by initrdmk** [comment]
I think you also need to change the `io.sockets.sockets[socketid] ` in signaling server into the 1.x version.

According to [this issue](https://github.com/Automattic/socket.io/issues/1618), `io.to(socketid)` or `io.sockets.connected[socketid]` may work.

I tried the former one and it works. However, I haven't fully tested it. Hope this helps. :)

**Comment by gmaliandi** [comment]
Perhaps I'm a little late, but I'll answer for the sake of those that reach this discussion searching how to solve the same problem (like me :P).

@lavende, in your code when you use `result.clients[client.id] = clients[client];` you're trying to access the property `id` of a string, because in that context `client` is just the name of the room.

Also, I debugged the object returned by `io.sockets.adapter.rooms[name]` and the values were not `socket` objects, but rather booleans. So in my implementation (https://github.com/gmaliandi/signalmaster/blob/patch-1/sockets.js) I stored the client's resources in a separate object, and referenced it using the socket.id (the only thing I could extract reliably from `io.sockets.adapter.rooms[name]`), like this:

```
function describeRoom(name) {
    var result = {
        clients: {}
    };
        
    var clients = io.sockets.adapter.rooms[name];
    if(clients) {
        Object.keys(clients).forEach(function (client) {
            result.clients[client] = resources[client];
        });
    }
        
    return result;
}
```

(where resources is an object where I store all clients resources by id)
