### ISSUE TITLE
Update Socket.IO dependency

### ISSUE THREAD

**Issue by matthiasg** [andyet/SimpleWebRTC#238]
Socket IO is currently at 1.x. thus the SimpleWebRTC examples dont work OOB since npm i socket.io defaults to 1.x and not 0.9 as it would have to be.

Any likelihood of upgrading soon ?

**Comment by xdumaine** [comment]
@matthiasg You can now pass in your own connection object to message on. See [this PR](https://github.com/HenrikJoreteg/SimpleWebRTC/pull/210) that added this feature for details on how (it's not documented in an example yet). We don't want to upgrade the default connection to socket.io because of the co-upgrade dependency with signalmaster, and we don't want to break existing deploys. Could you take a look at that PR and either close this issue or update it with more details?
