### ISSUE TITLE
Dark Images

### ISSUE THREAD

**Issue by thomastthai** [andyet/SimpleWebRTC#509]
At night time, the video images are very dark on both the phone and laptop with SimpleWebRTC. Using the native photo/camera app the image is bright. Attached are the same scene in the same lighting condition. Chrome on my Note 4 show the worst disparity (photos below). The laptop was slightly different in favor of lighting using Windows 10 Camera app and SimpleWebRTC video.

![screenshot_2016-11-15-22-11-01](https://cloud.githubusercontent.com/assets/16532581/20336745/72da0b88-ab81-11e6-9b52-c26425913f34.png)
![screenshot_2016-11-15-22-11-11](https://cloud.githubusercontent.com/assets/16532581/20336746/72ddc14c-ab81-11e6-8021-ae120533dd02.png)

**Comment by fippo** [comment]
I've noticed similar things but there is not much we can do here. Can you file a browser bug -- either http://crbug.com/ for Chrome or https://bugzilla.mozilla.org/ for Mozilla?

**Comment by thomastthai** [comment]
What is the cause of it. I saw several reports of it from Googling under
WebRTC but no resolution.

On Nov 15, 2016 10:42 PM, "Philipp Hancke" <notifications@github.com> wrote:

I've noticed similar things but there is not much we can do here. Can you
file a browser bug -- either http://crbug.com/ for Chrome or
https://bugzilla.mozilla.org/ for Mozilla?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/andyet/SimpleWebRTC/issues/509#issuecomment-260866928>,
or mute the thread

**Comment by fippo** [comment]
I think it depends on how the camera is opened by the application. Maybe @KaptenJansson knows someone who knows more?

**Comment by thomastthai** [comment]
I submitted a bug report using an existing report where there was no
further progress.

**Comment by KaptenJansson** [comment]
I believe this boils down to how the app is using the camera, a camera app most likely has it's own logic to configure the camera according to it's modes. 

Currently WebRTC does not have any "knobs" for adjusting camera settings except FPS, aspect ratio and resolution when initially opening the camera, i.e. these cannot be adjusted on the fly without reopening the camera which will affect the user experience due to having to shut down the camera and start it up again etc. Maybe more could be done by requesting a certain mode from the [camera2 ap](https://developer.android.com/reference/android/hardware/camera2/package-summary.html)i where it tries to achieve a certain brightness rather than a adhering to a specific FPS (which is currently a best effort). No expert in that area though...
