### ISSUE TITLE
Weird audio situation

### ISSUE THREAD

**Issue by Type-40** [andyet/SimpleWebRTC#587]
I am getting no errors. And I am not able to exactly replicate my problem. It started this morning. 

I have 4 different computers on 3 networks. 

Computer A on network A sends audio out and recieves audio all the time.

Computer B on Network B does not recieve Audio from computer C

Computer C on Network C recieves audio from A and B 

Computer D recieves audio from C but does not send to C .

I get no errors. microphones are connected and work with other apps. Video connects fine. 
I tested with Appear.in and same issues with same configuration. I cant figure out why some computers just wont have audio from certain other ones,,,,...

**Comment by Type-40** [comment]
BTW, this happens on chrome and firefox

**Comment by Type-40** [comment]
its like a roll of the dice to see who can hear who everytime i connect.

**Comment by Type-40** [comment]
On the computers with the problem I paused the video mid call in appr.tc then resumed this. This seemed to fix everything .... still not sure why.

**Comment by Type-40** [comment]
Why was this closed ?

**Comment by xdumaine** [comment]
Because you commented "this seemed to fix everything." I guess I misunderstood. However, You'd need to provide more details (like webrtc-internals dumps, turn server config, etc) before we can be much help here. Additionally, since you mentioned you tested with Appear.in and got the same behavior, that rules out this being an issue with this library. I'd recommend posting on the discuss-webrtc discussion board, since this is a general webrtc related problem, not one specific to this library.

**Comment by Type-40** [comment]
Fair enough, i have posted there as well. Still waiting to see where the errors came from... Thank you
